version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tele-server
    ports:
      - "5050:5050"
    environment:
      NODE_ENV: production
      MONGODB_URI: "mongodb://teleadmin:E7Dw~e5NKh4Ly's@mongo:27017/TeleProd?authSource=admin"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
  mongo:
    container_name: basilia-db
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: teleadmin
      MONGO_INITDB_ROOT_PASSWORD: E7Dw~e5NKh4Ly's
      MONGO_INITDB_DATABASE: TeleProd
    volumes:
      - mongoData:/data/db
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: teleadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: E7Dw~e5NKh4Ly's
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: teleadmin
      ME_CONFIG_BASICAUTH_PASSWORD: E7Dw~e5NKh4Ly's
    depends_on:
      - mongo
volumes:
  mongoData:
